export const COUNTRIES = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "NL", name: "Netherlands" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "BE", name: "Belgium" },
  { code: "DK", name: "Denmark" },
  { code: "NO", name: "Norway" },
  { code: "FI", name: "Finland" },
  { code: "IE", name: "Ireland" },
  { code: "AT", name: "Austria" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "PL", name: "Poland" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "JP", name: "Japan" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "IN", name: "India" },
  { code: "AE", name: "UAE" },
  { code: "IL", name: "Israel" },
  { code: "NZ", name: "New Zealand" },
  { code: "ZA", name: "South Africa" },
  { code: "CZ", name: "Czech Republic" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Romania" },
  { code: "HU", name: "Hungary" },
  { code: "GR", name: "Greece" },
  { code: "TR", name: "Turkey" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "ID", name: "Indonesia" },
  { code: "PH", name: "Philippines" },
  { code: "VN", name: "Vietnam" },
];

export const SENIORITY_OPTIONS = [
  { value: "founder", label: "Founder / Co-Founder" },
  { value: "c_suite", label: "C-Suite (CEO, CTO, CFO, COO, CMO, CRO, CIO, CISO, CHRO)" },
  { value: "vp", label: "VP / SVP / EVP" },
  { value: "head", label: "Head of / Director" },
  { value: "director", label: "Director" },
  { value: "manager", label: "Manager / Lead / Principal" },
  { value: "ic", label: "Individual Contributor / Staff / Senior" },
];

export const DEPARTMENT_OPTIONS = [
  { value: "marketing", label: "Marketing / Growth" },
  { value: "sales", label: "Sales / Business Development" },
  { value: "engineering", label: "Engineering / R&D" },
  { value: "product", label: "Product" },
  { value: "finance", label: "Finance / Accounting" },
  { value: "hr", label: "HR / People / Talent" },
  { value: "operations", label: "Operations" },
  { value: "legal", label: "Legal / Compliance" },
  { value: "it", label: "IT / Information Technology" },
  { value: "customer success", label: "Customer Success / Support" },
];

export const INDUSTRY_OPTIONS = [
  { value: "SaaS", label: "SaaS / Software" },
  { value: "E-commerce", label: "E-commerce / Marketplace" },
  { value: "Fintech", label: "Fintech / Payments" },
  { value: "Healthcare", label: "Healthcare / Biotech / Medtech" },
  { value: "Logistics", label: "Logistics / Supply Chain" },
  { value: "Agency", label: "Agency / Consulting / Services" },
  { value: "EdTech", label: "EdTech" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "AI/ML", label: "AI / Machine Learning" },
  { value: "Crypto/Web3", label: "Crypto / Web3" },
  { value: "Gaming", label: "Gaming" },
  { value: "Media", label: "Media / Content / Creator Economy" },
  { value: "Real Estate", label: "Real Estate / PropTech" },
  { value: "Manufacturing", label: "Manufacturing / Industrial" },
  { value: "Energy", label: "Energy / CleanTech / Climate" },
  { value: "Automotive", label: "Automotive / Mobility" },
  { value: "Nonprofit", label: "Nonprofit / Education / Government" },
];

export const COMPANY_TYPE_OPTIONS = [
  { value: "Privately Held", label: "Privately Held" },
  { value: "Public Company", label: "Public Company" },
  { value: "Nonprofit", label: "Nonprofit" },
  { value: "Partnership", label: "Partnership" },
  { value: "Self-Employed", label: "Self-Employed" },
  { value: "Government Agency", label: "Government Agency" },
  { value: "Educational", label: "Educational Institution" },
];

export const EMPLOYEE_RANGE_OPTIONS = [
  { value: "1-10", label: "1-10" },
  { value: "11-50", label: "11-50" },
  { value: "51-200", label: "51-200" },
  { value: "201-500", label: "201-500" },
  { value: "501-1000", label: "501-1000" },
  { value: "1001-5000", label: "1001-5000" },
  { value: "5001-10000", label: "5001-10000" },
  { value: "10001+", label: "10001+" },
];

// Common job titles for autocomplete
export const POPULAR_TITLES = [
  "CEO", "Co-Founder", "Founder", "CTO", "CFO", "COO", "CMO", "CRO", "CIO", "CISO", "CHRO",
  "VP Engineering", "VP Sales", "VP Marketing", "VP Product", "VP Operations", "VP Finance",
  "SVP Engineering", "SVP Sales", "SVP Marketing",
  "Head of Engineering", "Head of Sales", "Head of Marketing", "Head of Product", "Head of Growth",
  "Director of Engineering", "Director of Sales", "Director of Marketing", "Director of Product",
  "Engineering Manager", "Sales Manager", "Marketing Manager", "Product Manager", "Growth Manager",
  "Tech Lead", "Team Lead", "Staff Engineer", "Principal Engineer", "Senior Engineer",
  "Account Executive", "Sales Development Rep", "Business Development Manager",
  "Marketing Director", "Growth Lead", "Demand Generation Manager",
  "Product Marketing Manager", "Product Designer", "UX Designer",
  "Data Scientist", "ML Engineer", "Data Engineer",
  "DevOps Engineer", "Platform Engineer", "Site Reliability Engineer",
  "Solutions Engineer", "Sales Engineer", "Customer Success Manager",
];